### ISSUE TITLE
sriov目前不支持在pod中插入多张sriov网卡

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/cni-plugins#35]
**What happend**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

**Comment by cyclinder** [comment]
是支持的，多张网卡需要在 Pod 的 yaml中声明 多个 sriov device resources 的定义:
```
        resources:
          limits:
            intel.com/sriov_netdevice: "2"
          requests:
            intel.com/sriov_netdevice: "2"
```
